version: '3'

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    volumes:
      - ./server:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'

  php:
    build: ./docker/php
    container_name: php
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: laravel_photo_dev
      DB_USER: root
      DB_PASS: password
    volumes:
      - ./server:/var/www

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:delegated
      - ./docker/mysql/log:/var/log/mysql:delegated
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  redis:
    build: ./docker/redis
    container_name: redis
    ports:
      - '6379:6379'